### ISSUE TITLE
dataset加载失败

### ISSUE THREAD

**Issue by sanyu6** [YiyanXu/DiffRec#3]
你好，我尝试使用“ sh run.sh amazon-book_clean 5e-5 0 400 [1000] 10 x0 5 0.0001 0.0005 0.005 0 1 log 1 0 ” 命令运行代码，但是在amazon-book 数据集加载过程中出现 ValueError: cannot reshape array of size 4566535 into shape (2283281,2)。

**Comment by Yewx0310** [comment]
请问您是怎么解决的呢？我在windows上不会有这个问题，但是放到ubuntu上就有这个问题出现

**Comment by sanyu6** [comment]
我当时的原因是，数据集下载时有点问题，文件应该没下载完整

**Comment by Yewx0310** [comment]
好的那我再试试
